### ISSUE TITLE
Lack of explicit box-sizing causes the badge to be the wrong size

### ISSUE THREAD

**Issue by CDWimmer** [Rapsssito/github-profile-badge#2]
I had `* { box-sizing: border-box;}` in the css of my page, and for whatever reason this leads to the hover width being miscalculated and too short to reveal the entire username. 
Turns out I have no idea _why_ that was in my css so I've removed it, but it seems like something that should be set explicitly to whatever the default value is rather than being at the whim of whatever is in the global css?

**Comment by Rapsssito** [comment]
@CDWimmer, thanks for the feedback! I will work on a fix ASAP.
